# Generated by Django 4.2.7 on 2026-02-17 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Icon class name", max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="trainers/"),
                ),
                ("experience_years", models.IntegerField(default=0)),
                ("certifications", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("weight", models.FloatField(help_text="Weight in kg")),
                ("height", models.FloatField(help_text="Height in cm")),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("active", "Active"),
                            ("veryActive", "Very Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maintenance_calories", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("food_name", models.CharField(max_length=200)),
                ("calories", models.FloatField()),
                ("servings", models.FloatField(default=1)),
                ("total_calories", models.FloatField()),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_logs",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
    ]
